### ISSUE TITLE
The network is unstable and the model cannot be downloaded at all

### ISSUE THREAD

**Issue by bengenseo** [john-mnz/ComfyUI-Inspyrenet-Rembg#14]
The network is unstable and I can't download it. It keeps interrupting and doesn't tell me where the model is stored. I can't run it at all.

**Comment by bengenseo** [comment]
v1-5-pruned-emaonly.ckptWhere should I put it!!!\models\checkpoints is wrong again

**Comment by john-mnz** [comment]
as of now the model goes to ".transparent-background/model ckpt_base.pth" in the pc's root user folder.
here is a link to download the model manually 
ckpt_base.pth:
https://github.com/plemeri/transparent-background/releases/download/1.2.12/ckpt_base.pth
