### ISSUE TITLE
Batch Process Image using WAS-suite Problem

### ISSUE THREAD

**Issue by mrteo12** [john-mnz/ComfyUI-Inspyrenet-Rembg#7]
Amazing node but with Batch process is not working, can check please? :(((
![image](https://github.com/user-attachments/assets/469f95e8-a4e8-42a8-9b75-0471a09cf81b)

**Comment by john-mnz** [comment]
can you provide the workflow you're using so I can reproduce the problem and fix it?

**Comment by john-mnz** [comment]
I'm closing because no further answer
